name: unleash
description: A Server Side Dart SDK for Unleash. Unleash is an open-source feature flag service.
version: 0.4.1
homepage: https://github.com/ivarconr/unleash-client-dart
repository: https://github.com/ivarconr/unleash-client-dart
issue_tracker: https://github.com/ivarconr/unleash-client-dart/issues

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  meta: ^1.16.0
  http: ^1.4.0
  path: ^1.9.1

dev_dependencies:
  coverage: ^1.13.1
  test: ^1.26.0
  yaml: ^3.1.3
  lints: ^5.1.1